name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Go Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest] # TODO(adam): support windows-latest with libxml2
    steps:
    # Install some dependencies, see the jbowtie/ratago for more information
    #
    # https://github.com/jbowtie/ratago#installation
    - name: Install Linux Dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y pkg-config libxml2 xsltproc wget xfonts-75dpi xfonts-base
        cd /tmp
        wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.bionic_amd64.deb
        sudo dpkg -i wkhtmltox_0.12.6-1.bionic_amd64.deb
        sudo apt -f install

    - name: Install macOS Dependencies
      if: runner.os == 'macOS'
      run: |
        brew install pkg-config libxml2 libxslt
        sudo ln -s /usr/local/opt/libxml2/include/libxml2/libxml /usr/local/include/libxml
        brew install icu4c wkhtmltopdf

    # - name: Install Windows Dependencies
    #   if: runner.os == 'Windows'
    #   run: choco install -y xsltproc

    - name: Install Deps
      env:
        GO111MODULE: "on"
      run: |
        go install github.com/jbowtie/ratago@latest

    # Setup Go and start our checks
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    # - name: Install make (Windows)
    #   if: runner.os == 'Windows'
    #   run: choco install -y make mingw

    - name: Check
      run: make check

    - name: Upload Code Coverage
      if: runner.os == 'Linux'
      run: bash <(curl -s https://codecov.io/bash)
